version: '2.1'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    network_mode: "host"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /media/data/docker-persist/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    depends_on:
      mosquitto:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 6

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    user: "1000:1000"
    ports:
      - 1883:1883
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/data/docker-persist/homeassistant/mosquitto/config:/mosquitto/config:ro
      - /media/data/docker-persist/homeassistant/mosquitto/data:/mosquitto/data
    restart: on-failure
